FROM python:3.8-slim

WORKDIR /myapp

COPY . /myapp

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

ENV NAME World

# Run app.py when the container launches
CMD ["python", "greet.py"]
